# Generated by Django 4.1.1 on 2022-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='photo',
            field=models.ImageField(blank=True, default='images/home.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/user.jpg', upload_to='images/'),
        ),
    ]
