# Generated by Django 4.1.1 on 2022-10-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rent_photo_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='modified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
